Update create-release.yml

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -29,72 +29,36 @@ jobs:
         ls -al Rime/
         pwd
 
-    - name: Zip yong.ini and mb directory
+    - name: Create directories
       run: |
         mkdir -p mb/xmjd6  # Ensure the directory exists
+
+    - name: Merge all .txt files and add header, remove extra newline after [DATA]
+      run: |
+        header='name=星猫键道6\nkey=`abcedfghijklmnopqrstuvwxyz;\\\nlen=12\nwildcard=~\nbihua=viuoa\ncode_e2=p11+p12+p21+p22+p13+p23\ncode_e3=p11+p21+p31+p13+p23+p33\ncode_a4=p11+p21+p31+n11+p13+p23+p33\n[DATA]'
+        echo -e "$header" > Rime/xmjd6.header.txt
+        cat Rime/*.txt > Rime/xmjd6.body.txt
+        echo -n "$(cat Rime/xmjd6.header.txt Rime/xmjd6.body.txt)" > mb/xmjd6/xmjd6.txt
+        rm Rime/xmjd6.header.txt Rime/xmjd6.body.txt
+
+    - name: Zip xmjd6.txt file
+      run: |
+        if [ -f mb/xmjd6/xmjd6.txt ]; then
+          zip -j mb/xmjd6.zip mb/xmjd6/xmjd6.txt
+          echo "xmjd6.txt has been successfully zipped."
+        else
+          echo "Error: xmjd6.txt does not exist in the mb/xmjd6 directory."
+          exit 1
+        fi
+
+    - name: Zip yong.ini and mb directory
+      run: |
         echo "Dummy content for yong.ini" > yong.ini  # Creating a dummy yong.ini file for example
         zip -r yong-xmjd6.zip yong.ini mb/
 
-    - name: Get latest release tag
-      id: get_tag
-      uses: actions/github-script@v7
-      with:
-        script: |
-          const response = await github.rest.repos.getLatestRelease({
-            owner: 'amorphobia',
-            repo: 'rabbit',
-          });
-          const tagName = response.data.tag_name;
-          console.log(`Latest release tag is ${tagName}`);
-          return tagName;
-
-    - name: Fetch tags and generate changelog from last release
-      id: changelog
-      uses: actions/github-script@v7
-      with:
-        script: |
-          const lastRelease = await github.rest.repos.getLatestRelease({
-            owner: context.repo.owner,
-            repo: context.repo.repo
-          });
-          const compare = await github.rest.repos.compareCommits({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            base: lastRelease.data.tag_name,
-            head: 'main'
-          });
-          let changelog = '';
-          compare.data.commits.forEach(commit => {
-            const message = commit.commit.message.split('\n').join(' ');
-            const commitLink = `[${commit.sha.substring(0, 7)}](https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${commit.sha})`;
-            changelog += `- ${commitLink} ${message} \n`;
-          });
-          core.setOutput('changelog', changelog);
-
-    - name: Set the tag as environment variable
-      run: echo "RELEASE_TAG=${{ steps.get_tag.outputs.result }}" >> $GITHUB_ENV
-    
-    - name: Download the release asset
+    - name: Create Rabbit-xmjd6.zip with SharedSupport
       run: |
-        curl -L -o rabbit-${{ env.RELEASE_TAG }}.zip https://github.com/amorphobia/rabbit/releases/download/${{ env.RELEASE_TAG }}/rabbit-${{ env.RELEASE_TAG }}-x64.zip
-      
-    - name: Unzip Rabbit
-      run: |
-        mkdir -p Rabbit
-        unzip rabbit-${{ env.RELEASE_TAG }}.zip -d Rabbit
-
-    - name: Clean SharedSupport
-      run: |
-        mkdir -p /tmp/Rabbit_backup
-        cp Rabbit/SharedSupport/punctuation.yaml /tmp/Rabbit_backup/
-        cp Rabbit/SharedSupport/key_bindings.yaml /tmp/Rabbit_backup/
-        cp Rabbit/SharedSupport/default.yaml /tmp/Rabbit_backup/
-        rm -rf Rabbit/SharedSupport/*
-        cp /tmp/Rabbit_backup/* Rabbit/SharedSupport/
-        rm -rf /tmp/Rabbit_backup
-
-    - name: Merge Rime into Rabbit
-      run: |
+        mkdir -p Rabbit/SharedSupport
         cp -r Rime/. Rabbit/SharedSupport
         zip -r Rabbit-xmjd6.zip Rabbit/
 
@@ -108,13 +72,12 @@ jobs:
         release_name: ${{ env.RELEASE_TITLE }}
         body: |
           ## Changelog
-          ${{ steps.changelog.outputs.changelog }}
           ## Release Notes
           - [如何使用](https://github.com/hugh7007/xmjd6-rere#如何使用)
         draft: false
         prerelease: false
 
-    - name: Upload Rabbit-xmjd6.zip to Release
+    - name: Upload all zipped files to Release
       uses: shogo82148/actions-upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -123,21 +86,11 @@ jobs:
         asset_path: ./Rabbit-xmjd6.zip
         asset_name: Rabbit-xmjd6.zip
         asset_content_type: application/zip
-
-    - name: Upload yong-xmjd6.zip to Release
-      uses: shogo82148/actions-upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./yong-xmjd6.zip
         asset_name: yong-xmjd6.zip
         asset_content_type: application/zip
-
-    - name: Upload xmjd6.zip to Release
-      uses: shogo82148/actions-upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./xmjd6.zip
